### ISSUE TITLE
Text in white when using a Dark Theme

### ISSUE THREAD

**Issue by lfom** [lwindolf/gedit-shellcheck#2]
Hello!

The output in the bottom panel is very hard to read when using a dark theme because the text is white. Adding a line with:

`renderer.props.foreground = "black"`

right after:

https://github.com/lwindolf/gedit-shellcheck/blob/192d199ad17afc91914fd293347eb1f8440c904d/shellcheck/outputpanel.py#L38

fixed the problem. The text automatically changes to white when selected, like the screenshot shown in the README.

Pop!_OS 20.10, like Ubuntu 20.10 (Gnome 3.38.3/GTK+3).

Regards

**Comment by lwindolf** [comment]
Fixed by merging #3 

Thanks for reporting!
